### ISSUE TITLE
Override factory or wrapped instance?

### ISSUE THREAD

**Issue by Tinche** [ionelmc/python-lazy-object-proxy#14]
Hi,

this isn't really a bug report, just a question. Is it possible to override the factory function before the proxy has been called the first time? Main use case would be test fixtures.

**Comment by ionelmc** [comment]
Hey, you can set `__factory__`. There are even some testcases for such use: https://github.com/ionelmc/python-lazy-object-proxy/blob/master/tests/test_lazy_object_proxy.py#L1708-L1746

**Comment by Tinche** [comment]
Thanks for the tip!
