### ISSUE TITLE
subclassing Proxy for lazy attribute raises TypeError

### ISSUE THREAD

**Issue by bagerard** [ionelmc/python-lazy-object-proxy#15]
Hi,
I'm trying to subclass Proxy in order to add some attribute that I could access without calling the proxied object.
```
from lazy_object_proxy import Proxy

class Foo:
    pass

class LazyProxy(Proxy):
    def __init__(self, func, **lazy_attr):
        Proxy.__init__(self, func)
        for attr, val in lazy_attr.items():
            object.__setattr__(self, attr, val)

proxy = LazyProxy(lambda: Foo(), name='bar')  # TypeError: can't apply this __setattr__ to Proxy object
```
Could you let me know if there is a way to achieve this?
Thanks!

**Comment by ionelmc** [comment]
Can you know ahead all the possible keys in `**lazy_attr`? If not I'm afraid the C extension might not be the best choice (there are two python implementations available tho).

**Comment by bagerard** [comment]
No, I wanted it to be generic but I'm fine with the python implementations, it works perfectly! Thanks for the quick feedback!

**Comment by ionelmc** [comment]
See examples in https://github.com/ionelmc/python-lazy-object-proxy/commit/7e499cd98b6a5f79d9bc43ebe509cb0e81b0aa4c

**Comment by sauravshah** [comment]
@ionelmc which are the python implementations that you are talking about?

**Comment by ionelmc** [comment]
@sauravshah either `lazy_object_proxy.simple.Proxy` or `lazy_object_proxy.slots.Proxy`

**Comment by sauravshah** [comment]
@ionelmc Thanks!
