### ISSUE TITLE
Exceptions from Factory

### ISSUE THREAD

**Issue by ztane** [ionelmc/python-lazy-object-proxy#3]
My factory raised an exception by accident; the factory was retried recursively until the recursion limit was hit; maybe an exception should be thrown earlier.

**Comment by ionelmc** [comment]
Hey @ztane, can you show me the start of the traceback and what was the exception?

**Comment by ztane** [comment]
yeah, it took quite some time to debug, the thing was, the factory threw an AttributeError :D

    from lazy_object_proxy.slots import Proxy
    foo = Proxy(lambda: None.nosuchattribute)
    foo.anything

**Comment by ztane** [comment]
Thus an AttributeError from the factory ought to be reraised wrapped in another exception.

**Comment by ionelmc** [comment]
It looks like you've found a but in the Proxy :grin: 

What if AttributeError is just reraised (and no infinite recursion)? That's how the cext implementation works now. The bug is present in the slots and simple implementations.

**Comment by ionelmc** [comment]
Thanks for the report.
