### ISSUE TITLE
setup_requires breaks pip with Python 3.5 on macOS

### ISSUE THREAD

**Issue by pquentin** [ionelmc/python-lazy-object-proxy#30]
I'd like to mention that [using setup_requires](https://github.com/ionelmc/python-lazy-object-proxy/commit/fdc7797e9947dfe512a21173c2276324e32a9a87) breaks pip with Python 3.5 on macOS because setup_requires dependencies are installed by easy_install, which uses the system OpenSSL, which only supports TLS 1.1 on macOS + Python 3.5. But PyPI only allows TLS 1.2.

See https://github.com/urllib3/urllib3/pull/1587#issuecomment-491692837 for more details if you're interested. I don't think this requires an action on your part, but I thought it would be useful to record this here.

**Comment by ionelmc** [comment]
Hmmm ... does anyone actually use 3.5 on osx?

**Comment by pquentin** [comment]
I guess it's mostly used by people who run Python 3.5 in production on eg. Debian but develop locally on macOS. So that's not a lot of people!

**Comment by scddev** [comment]
This also breaks with newer python, in my case python 3.7.1 on Solaris.

**Comment by ionelmc** [comment]
Would using pyproject.toml help? Latest pip would handle the setuptools-scm dep then.

**Comment by ionelmc** [comment]
@scddev try the master, you shouldn't need that workaround.

**Comment by pquentin** [comment]
Ah, that's a great idea! It's a bit hard for me to test without a release on PyPI though. Maybe @scddev will be able to do it.

**Comment by scddev** [comment]
Worked for me:

```
-bash-3.2$ python3 -m venv .venv
-bash-3.2$ source .venv/bin/activate
(.venv) -bash-3.2$ python3 -m pip install --upgrade pip
Looking in indexes: https://xxx/artifactory/api/pypi/pypi-org/simple
Collecting pip
  Using cached https://xxx/artifactory/api/pypi/pypi-org/packages/5c/e0/be401c003291b56efc55aeba6a80ab790d3d4cece2778288d65323009420/pip-19.1.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 10.0.1
    Uninstalling pip-10.0.1:
      Successfully uninstalled pip-10.0.1
Successfully installed pip-19.1.1
(.venv) -bash-3.2$ cd python-lazy-object-proxy/
(.venv) -bash-3.2$ python3 -m pip install -e .         
Looking in indexes: https://xxx/artifactory/api/pypi/pypi-org/simple
Obtaining file:///tmp/scd/python-lazy-object-proxy
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Installing collected packages: lazy-object-proxy
  Running setup.py develop for lazy-object-proxy
Successfully installed lazy-object-proxy
(.venv) -bash-3.2$ uname -a
SunOS yyy 5.10 Generic_Virtual sun4v sparc sun4v
(.venv) -bash-3.2$ python -V
Python 3.7.1
```
