### ISSUE TITLE
Request for new release to include pyproject.toml

### ISSUE THREAD

**Issue by ericvw** [ionelmc/python-lazy-object-proxy#32]
Hello.  I was wondering if a new release of `lazy-object-proxy` could be cut to include the changes in https://github.com/ionelmc/python-lazy-object-proxy/commit/4e2b00e6e3b2e903e0e0b3f0f207b69678a24c3e?

This would greatly simplify using `pip install` when `lazy-object-proxy` to not go through the `setuptools`' `setup_requires` (calling `easy_install`) mechanism. 

Thanks!

**Comment by gpiks** [comment]
Would this be needed anymore? Looks like I can build without it.
https://github.com/ionelmc/python-lazy-object-proxy/blob/master/setup.cfg#L1-L3

**Comment by gpiks** [comment]
> Would this be needed anymore? Looks like I can build without it.

It would still be needed for users who invoke `setup.py` directly.  @ericvw clarified it offline :)

**Comment by ionelmc** [comment]
If it doesn't happen tomorrow ping me again, I forget things.

**Comment by gpiks** [comment]
Just pinging as a reminder :)

**Comment by ionelmc** [comment]
Released 1.4.2.
