### ISSUE TITLE
1.4.3: wrong version in generated PKG-INFO?

### ISSUE THREAD

**Issue by kloczek** [ionelmc/python-lazy-object-proxy#37]
```
Metadata-Version: 1.2
Name: lazy-object-proxy
Version: 0.0.0                                         <<== HERE
Summary: A fast and thorough lazy object proxy.
Home-page: https://github.com/ionelmc/python-lazy-object-proxy
Author: Ionel Cristian Mărieș
Author-email: contact@ionelmc.ro
```

**Comment by ionelmc** [comment]
Where are you getting this metadata from?

**Comment by kloczek** [comment]
After standard build and install procedure
```
+ /usr/bin/python3 setup.py build '--executable=/usr/bin/python3 -s'
+ /usr/bin/python3 setup.py install -O1 --skip-build --root /home/tkloczko/rpmbuild/BUILDROOT/python-lazy-object-proxy-1.4.3-4.fc33.x86_64
```
That is begin of the /home/tkloczko/rpmbuild/BUILDROOT/usr/lib64/python3.8/site-packages/lazy_object_proxy-0.0.0-py3.8.egg-info/PKG-INFO

**Comment by ionelmc** [comment]
This project is using setuptools-scm. If you build from sources you need to have git installed. Perhaps you can install the sdist from pypi. That has the right metadata baked in (doesn't require git).

**Comment by kloczek** [comment]
I have git installed and setuptools-scm module.

I suppose only that you test procedure assumes that it will be done **in cloned git directory**.
If that is true it means that putting dist tar balls on https://pypi.org/project/lazy-object-proxy/ is pointless because those archives does not have git meta data.

**Comment by ionelmc** [comment]
They do have the metadata, and they do include the tests. Use those instead of a shallow git clone.

**Comment by ionelmc** [comment]
If that don't work post the complete spec because it's impossible for me to guess how you're building the rpm.

**Comment by kloczek** [comment]
OK my fault. I've been using git archive from git tag.

Tar from https://pypi.org/project/lazy-object-proxy/ is with correct setup.cfg with fallback to version 1.4.3 if it is not possible to obtain version from git.

Closing.
