### ISSUE TITLE
Error when install: the project doesn't specify a build backend

### ISSUE THREAD

**Issue by suliveevil** [ionelmc/python-lazy-object-proxy#42]
![39BC7A6D-7C81-4120-8175-735EA893D39F](https://user-images.githubusercontent.com/35763237/85945033-8ad4d800-b96d-11ea-8741-f3f912ae914c.png)

**Comment by ionelmc** [comment]
This looks like a pip bug, either it's broken or the message that it give is misleading. This project does declare the build deps (including wheel) in pyproject.toml. Perhaps you can workaround this problem by updating pip or installing wheel before attempting the install?

**Comment by suliveevil** [comment]
Thank you very much.
