### ISSUE TITLE
Support `async with` and other asyncio-specific object methods

### ISSUE THREAD

**Issue by garyd203** [ionelmc/python-lazy-object-proxy#49]
Is it possible to add proxy hooks to wrap the special methods used by `async with` and other asyncio-specific syntax?

**Comment by ionelmc** [comment]
Yes, will add them.

**Comment by ionelmc** [comment]
I hope you'll help with beta-testing this cause I'm pretty sure I won't be able to figure out all the corner cases from the first try :-)

**Comment by garyd203** [comment]
Absolutely! I don't have very sophisticated needs myself, but certainly happy to give a beta version a run - just let me know when and how

**Comment by ionelmc** [comment]
Ooof I almost gave up, the async apis are quite messy with lots of shortcircuits in the interpreter. I got the slots/simple implementations working in  https://github.com/ionelmc/python-lazy-object-proxy/tree/async-methods - give em a try.

The cext (default one) is currently broken until I figure out a better way to implement `__await__` 😕

**Comment by garyd203** [comment]
Thanks @ionelmc that's really helpful of you. I unfortunately don't have time to try it out this week, but I will give it a go on my use case next week.
