### ISSUE TITLE
Linux wheels for version 1.8.0

### ISSUE THREAD

**Issue by Mscht** [ionelmc/python-lazy-object-proxy#73]
Hello,
can you please provide the linux wheels on PyPi like you did for previous versions? It just leads to unnecessary problems trying to build the library on local or virtual machines.

**Comment by ionelmc** [comment]
Whooops, I'll fix this.

**Comment by Mscht** [comment]
Thank you!

**Comment by ionelmc** [comment]
Released 1.9.0 and that should have all the wheels.
