### ISSUE TITLE
Provide none-any version without C extension

### ISSUE THREAD

**Issue by vit9696** [ionelmc/python-lazy-object-proxy#74]
Statically-compiled python interpreter cannot load C extensions as they are dynamic libraries. Could you please provide a version without the C extension on pypi and/or at least an easy way to build it without patches?

**Comment by ionelmc** [comment]
Try the SETUPPY_ALLOW_PURE env var.

**Comment by vit9696** [comment]
Thanks, will try. The second issue is that running setup.py requires setuptools_scm, which is optional when installing from a whl package.

**Comment by vit9696** [comment]
Tested. This partially works, on systems with non-statically linked python it still builds a dynamic library, which is undesired for unified testing.

**Comment by ionelmc** [comment]
I can add a skip flag but I'd like to understand a bit ... in your statically-compiled python project how are you installing all the other dependencies? I'd expect you'd use other packages not just lazy-object-proxy....

**Comment by ionelmc** [comment]
Sorry, the env var is SETUPPY_FORCE_PURE.
